//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Makale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Makale()
        {
            this.Yorums = new HashSet<Yorum>();
        }
    
        public System.Guid MakaleId { get; set; }
        public string Baslik { get; set; }
        public string Icerik { get; set; }
        public string Foto { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<System.Guid> KategoriId { get; set; }
        public Nullable<System.Guid> UyeId { get; set; }
        public string Okunma { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Üye Üye { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorum> Yorums { get; set; }
        public virtual Etiket Etiket { get; set; }
    }
}
